apiVersion: v1
kind: Service
metadata:
  name: springsvc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 30007  # Optional, Kubernetes will auto-assign if not provided

