apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdeployment
  namespace: test
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  minReadySeconds: 30
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
      - name: springcontainer
        image: dockerhandson/spring-boot-app:1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
          limits:
            cpu: 1
            memory: 256Mi
        env:
        - name: MONGO_DB_HOSTNAME
          value: mongosvc
        - name: MONGO_DB_USERNAME
          value: developer
        - name: MONGO_DB_PASSWORD
          value: devdb@123
